version: 2
updates:
- package-ecosystem: npm
  directory: "/leaflet_app/plugin/w8r-Leaflet.Bookmarks-7c2dee7"
  schedule:
    interval: daily
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.12.6
    - 3.12.7
    - 3.12.8
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: less
    versions:
    - 4.1.0
  - dependency-name: watchify
    versions:
    - 3.11.1
  - dependency-name: exorcist
    versions:
    - 1.0.1
- package-ecosystem: npm
  directory: "/leaflet_app/plugin/jQuery-UI-Multiple-Select-Widget"
  schedule:
    interval: daily
    timezone: America/New_York
  open-pull-requests-limit: 10
